# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('ultima_modificacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=20)),
                ('extension', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=28)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('ultima_modificacion', models.DateField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('aceptada', models.BooleanField()),
                ('importe', models.IntegerField()),
                ('cantidad_pagada', models.IntegerField(default=0)),
                ('ultima_modificacion', models.DateField(auto_now=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ultima_modificacion', models.DateField(auto_now=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=128)),
                ('precio', models.IntegerField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('ultima_modificacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Producto'),
        ),
    ]
