# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'verbose_name_plural': 'Cotizaciones'},
        ),
    ]
