# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-27 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20170527_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='puesto',
            new_name='departamento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(default='None', max_length=15),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default='None', max_length=15),
        ),
    ]
