# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-04-18 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20170527_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={},
        ),
    ]
